swagger: '2.0'
info:
  description: API des transactions de BilletBank, qui permet la récupération des transactions, ainsi que la mise à jour de ces dernières.
  version: 1.0.0
  title: BilletBank Transactions
  contact:
    email: pic.fab@hotmail.fr
host: "localhost:3001"
basePath: /api/v1/
schemes:
  - https
paths:
  /transactions:
    post:
      tags:
        - transactions
      summary: GET array of transactions
      description: 'GET array of objects transactions with a start and end date in millisecond'
      operationId: getTransactions
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "api_key"
          in: "header"
          required: true
          type: "string"
        - in: body
          name: body
          description: 'start and end of the begining transactions selected'
          required: true
          schema:
            $ref: '#/definitions/TransactionsDemand'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Invalid status value
        '403':
          description: The access rights do not allow to access the resource. Send a valid token
        '422':
          description: The params are not valid
        '498':
          description: The token has expired or is invalid.
      security:
        - api_key: []

  /transaction/{id}:
    post:
      tags:
        - transaction
      summary: GET a transaction
      description: 'GET a specific transaction with a id'
      operationId: getTransaction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "api_key"
          in: "header"
          required: true
          type: "string"
        - name: "id"
          in: "path"
          description: "ID of transaction to return"
          required: true
          type: "integer"
          format: "int64"

      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid status value
        '403':
          description: The access rights do not allow to access the resource. Send a valid token
        '422':
          description: The params are not valid
        '498':
          description: The token has expired or is invalid.
      security:
        - api_key: []

    put:
      tags:
        - transaction
      summary: Update a transaction
      description: 'Update notes or category of a transaction'
      operationId: updateTransaction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "api_key"
          in: "header"
          required: true
          type: "string"
        - name: "id"
          in: "path"
          description: "ID of transaction to return"
          required: true
          type: "integer"
          format: "int64"
        - in: body
          name: body
          description: 'If notes or categoryID empty, they will remove'
          required: false
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid status value
        '403':
          description: The access rights do not allow to access the resource. Send a valid token
        '404':
          description: Not transaction find
        '422':
          description: The params are not valid
        '498':
          description: The token has expired or is invalid.
      security:
        - api_key: []

securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Transaction:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        example: 1
        format: int64
      category:
        $ref: '#/definitions/Category'
      type:
        type: string
        example: Electronic
      balance:
        type: number
        example: 2097.04
      description:
        type: string
        example: Golden Sun Bakery
      notes:
        type: string
        example: A note about Golden Sun Bakery
      amount :
        type: number
        example: 5.15
      date:
        type: integer
        example: 1617173013966

  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string

  TransactionsDemand:
    type: object
    properties:
      start:
        type: number
        example: 1617173013966

      end:
        type: number
        example: 1617173013966


  TransactionUpdate:
    type: object
    properties:
      notes:
        type: string
        example: A note about Golden Sun Bakery

      categoryId:
        type: integer
        example: 1




